In [3]:
import pandas as pd

In [4]:
import numpy as np

In [12]:
data = pd.read_csv('C:\\Users\\prash\\Downloads\\spam3.csv')

In [13]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [14]:
data.tail()

v1                                                 v2 Unnamed: 2  \
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [16]:
data.isnull()

v1     v2  Unnamed: 2  Unnamed: 3  Unnamed: 4
0     False  False        True        True        True
1     False  False        True        True        True
2     False  False        True        True        True
3     False  False        True        True        True
4     False  False        True        True        True
...     ...    ...         ...         ...         ...
5567  False  False        True        True        True
5568  False  False        True        True        True
5569  False  False        True        True        True
5570  False  False        True        True        True
5571  False  False        True        True        True

[5572 rows x 5 columns]

In [17]:
data.iloc[:,1:2]

v2
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568              Will Ì_ b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [18]:
data.iloc[:,1:2].values

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [19]:
train=data.iloc[:,1:2].values

In [20]:
train

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
sc=MinMaxScaler()

In [25]:
scaling_train=sc.fit_transform(train)

ValueError: could not convert string to float: 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [28]:

data.boxplot('v1','v2',rot=30,figsize=(5,6))

<matplotlib.axes._subplots.AxesSubplot at 0x7f32ee10f550>

SyntaxError: invalid syntax (3680949187.py, line 2)

In [29]:
da=data.select_dtypes(include=['object']).copy()

In [30]:
da

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [32]:
print(da['v2'].value_counts())

Sorry, I'll call later                                                                                                                                                 30
I cant pick the phone right now. Pls send a message                                                                                                                    12
Ok...                                                                                                                                                                  10
7 wonders in My WORLD 7th You 6th Ur style 5th Ur smile 4th Ur Personality 3rd Ur Nature 2nd Ur SMS and 1st \Ur Lovely Friendship\"... good morning dear"               4
Say this slowly.? GOD,I LOVE YOU &amp; I NEED YOU,CLEAN MY HEART WITH YOUR BLOOD.Send this to Ten special people &amp; u c miracle tomorrow, do it,pls,pls do it...     4
                                                                                                                                                      

In [33]:
print(da['v2'].value_counts().count())

5169


In [35]:
 data['v2']=data['v2'].astype(float)

ValueError: could not convert string to float: 'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [36]:
from sklearn import preprocessing

In [44]:
def convert(data):
    num = preprocessing.LabelEncoder()
    data['v2']=num.fit_transform(data.v2)
    data=data.fillna(-999)
    return data
train=convert(data)
test=convert(data)

In [39]:
data['v2']=num.fit_transform(data.v2)

NameError: name 'num' is not defined

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   int64 
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: int64(1), object(4)
memory usage: 217.8+ KB


In [46]:
train=data.iloc[:,1:2].values

In [47]:
train


array([[1079],
       [3101],
       [1000],
       ...,
       [3286],
       [3901],
       [3409]], dtype=int64)

In [48]:
from sklearn.preprocessing import MinMaxScaler

In [49]:
sc=MinMaxScaler()

In [50]:
scaling_train=sc.fit_transform(train)

In [51]:
scaling_train

array([[0.20878483],
       [0.6000387 ],
       [0.19349845],
       ...,
       [0.63583591],
       [0.75483746],
       [0.65963622]])

In [52]:
x_train = []
y_train = []

for i in range(60,1258):
    x_train.append(scaling_train[i-60:i,0])
    y_train.append(scaling_train[i,0])

In [53]:
scaling_train[60-60:60,0]

array([0.20878483, 0.6000387 , 0.19349845, 0.79102167, 0.53347523,
       0.19543344, 0.17705108, 0.07120743, 0.82217492, 0.23916409,
       0.40363777, 0.66505418, 0.80205108, 0.41679567, 0.32585139,
       0.88815789, 0.58301084, 0.17221362, 0.187113  , 0.17356811,
       0.4369195 , 0.45259288, 0.69736842, 0.02883127, 0.18556502,
       0.46091331, 0.50174149, 0.14125387, 0.3999613 , 0.03037926,
       0.8246904 , 0.90073529, 0.47155573, 0.18866099, 0.73935759,
       0.95859133, 0.625387  , 0.37287152, 0.05824303, 0.26354489,
       0.64202786, 0.13893189, 0.00890093, 0.82082043, 0.22581269,
       0.54256966, 0.14299536, 0.18401703, 0.90092879, 0.79063467,
       0.86339009, 0.02341331, 0.46962074, 0.88660991, 0.66679567,
       0.14821981, 0.11648607, 0.71033282, 0.73006966, 0.91795666])

In [54]:
x-train

NameError: name 'x' is not defined

In [55]:
x_train

[array([0.20878483, 0.6000387 , 0.19349845, 0.79102167, 0.53347523,
        0.19543344, 0.17705108, 0.07120743, 0.82217492, 0.23916409,
        0.40363777, 0.66505418, 0.80205108, 0.41679567, 0.32585139,
        0.88815789, 0.58301084, 0.17221362, 0.187113  , 0.17356811,
        0.4369195 , 0.45259288, 0.69736842, 0.02883127, 0.18556502,
        0.46091331, 0.50174149, 0.14125387, 0.3999613 , 0.03037926,
        0.8246904 , 0.90073529, 0.47155573, 0.18866099, 0.73935759,
        0.95859133, 0.625387  , 0.37287152, 0.05824303, 0.26354489,
        0.64202786, 0.13893189, 0.00890093, 0.82082043, 0.22581269,
        0.54256966, 0.14299536, 0.18401703, 0.90092879, 0.79063467,
        0.86339009, 0.02341331, 0.46962074, 0.88660991, 0.66679567,
        0.14821981, 0.11648607, 0.71033282, 0.73006966, 0.91795666]),
 array([0.6000387 , 0.19349845, 0.79102167, 0.53347523, 0.19543344,
        0.17705108, 0.07120743, 0.82217492, 0.23916409, 0.40363777,
        0.66505418, 0.80205108, 0.41679567, 0.

In [56]:
y_train

[0.9496904024767803,
 0.23664860681114552,
 0.4465944272445821,
 0.7066563467492261,
 0.5998452012383901,
 0.0696594427244582,
 0.7809597523219814,
 0.8146284829721363,
 0.141640866873065,
 0.37093653250773995,
 0.8237229102167183,
 0.18788699690402477,
 0.23258513931888547,
 0.47774767801857587,
 0.7894736842105263,
 0.3343653250773994,
 0.7511609907120743,
 0.36416408668730654,
 0.15363777089783281,
 0.44891640866873067,
 0.7093653250773995,
 0.47484520123839014,
 0.5965557275541796,
 0.9446594427244582,
 0.9553018575851394,
 0.3363003095975232,
 0.18962848297213625,
 0.9100232198142415,
 0.41234520123839014,
 0.17279411764705882,
 0.90015479876161,
 0.7078173374613004,
 0.6890479876160991,
 0.6377708978328174,
 0.25386996904024767,
 0.9493034055727555,
 0.8347523219814242,
 0.9794891640866874,
 0.29702012383900933,
 0.6383513931888545,
 0.6151315789473685,
 0.4136996904024768,
 0.07120743034055728,
 0.9936145510835914,
 0.8080495356037152,
 0.7352941176470589,
 0.033862229102167185,

In [69]:
x_train1,y_train1 = np.array( x_train),np.array(y_train)


In [65]:
x_train1

array([[0.20878483, 0.6000387 , 0.19349845, ..., 0.71033282, 0.73006966,
        0.91795666],
       [0.6000387 , 0.19349845, 0.79102167, ..., 0.73006966, 0.91795666,
        0.9496904 ],
       [0.19349845, 0.79102167, 0.53347523, ..., 0.91795666, 0.9496904 ,
        0.23664861],
       ...,
       [0.93459752, 0.85739164, 0.25503096, ..., 0.90208978, 0.52573529,
        0.86358359],
       [0.85739164, 0.25503096, 0.03947368, ..., 0.52573529, 0.86358359,
        0.46613777],
       [0.25503096, 0.03947368, 0.53289474, ..., 0.86358359, 0.46613777,
        0.56830495]])

In [70]:
y_train1

array([0.9496904 , 0.23664861, 0.44659443, ..., 0.46613777, 0.56830495,
       0.04779412])

In [71]:
x_train1.shape

(1198, 60)

In [74]:
x_train2 = np.reshape(x_train1,(1198,60,1))

In [75]:
x_train2

array([[[0.20878483],
        [0.6000387 ],
        [0.19349845],
        ...,
        [0.71033282],
        [0.73006966],
        [0.91795666]],

       [[0.6000387 ],
        [0.19349845],
        [0.79102167],
        ...,
        [0.73006966],
        [0.91795666],
        [0.9496904 ]],

       [[0.19349845],
        [0.79102167],
        [0.53347523],
        ...,
        [0.91795666],
        [0.9496904 ],
        [0.23664861]],

       ...,

       [[0.93459752],
        [0.85739164],
        [0.25503096],
        ...,
        [0.90208978],
        [0.52573529],
        [0.86358359]],

       [[0.85739164],
        [0.25503096],
        [0.03947368],
        ...,
        [0.52573529],
        [0.86358359],
        [0.46613777]],

       [[0.25503096],
        [0.03947368],
        [0.53289474],
        ...,
        [0.86358359],
        [0.46613777],
        [0.56830495]]])

In [76]:
x_train2.shape

(1198, 60, 1)

In [2]:
from tensorflow.keras.models import Sequential

ModuleNotFoundError: No module named 'tensorflow'

In [79]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
--pip install tensorflow

SyntaxError: invalid syntax (339172089.py, line 1)